name: nightowl
description: A cute study timer app
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  lottie: ^2.2.0
  google_fonts: ^4.0.3
  shared_preferences: ^2.5.4  
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/backgrounds/
